import type { Metadata } from "next";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="light">
      <body className={`text-gray-900 antialiased bg-white`}>
        <Header />
        <main className="pt-30 flex flex-col">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
